imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator: { fallbacks: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig', 'ShtumiUsefulBundle::fields.html.twig', 'LexikFormFilterBundle:Form:form_div_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    port: 465
    encryption: ssl
    auth_mode: login
    logging: true

# Shtumi Useful Bundle Configuration
shtumi_useful:
    autocomplete_entities:
        comptes:
            class: AppBundle:CRM\Compte
            role: IS_AUTHENTICATED_ANONYMOUSLY
            property: nom
            search: contains
        contacts:
            class: AppBundle:CRM\Contact
            role: IS_AUTHENTICATED_ANONYMOUSLY
            property: nom
            search: contains

# FOS User Bundle Configuration
fos_user:
    service:
      mailer: fos_user.mailer.twig_swift
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: appbundle_user_registration
        confirmation:
            enabled: true
            template: "email/registration/confirmation.email.twig"
    resetting:
        email:
          template: "email/resetting/reset.email.twig"
    from_email:
        address:        laura@jaime-gerer.com
        sender_name:    J'aime gÃ©rer

# SONATA User Bundle
sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: AppBundle\Entity\User
        group: AppBundle\Entity\Group
    impersonating:
        route: homepage
    admin:
        user:
            class: Nicomak\UserBundle\Entity\UserAdmin
            controller: SonataAdminBundle:CRUD
            translation: SonataUserBundle

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.block.service.text:
        sonata.block.service.action: ~
        sonata.block.service.rss: ~
        sonata.admin.block.search_result: ~

sonata_admin:
    title:      Administration
    title_logo: /web/images/logo-couleur-500px.png
    templates:
        layout:     admin/admin_layout.html.twig

# KNP Snappy
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []

# TinyMCE
stfalcon_tinymce:
  include_jquery: false
  tinymce_jquery: false
  language: %locale%
  selector: ".tinymce"
  theme:
      simple:
          content_css : "/web/css/tinymce_content.css"
          mode: "textarea"
          theme: "advanced"
          menubar: false
          statusbar: false
          plugins: "textcolor link"
          toolbar: "bold italic underline | forecolor | alignleft aligncenter alignright alignjustify | bullist numlist | link"
          theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
          theme_advanced_buttons2: ""
          theme_advanced_buttons3: ""
          theme_advanced_toolbar_location: "top"
          theme_advanced_toolbar_align: "left"
          theme_advanced_statusbar_location: "bottom"
      advanced:
                 plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                 toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                 toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
                 image_advtab: true
                 templates:
                     - {title: 'Test template 1', content: 'Test 1'}
                     - {title: 'Test template 2', content: 'Test 2'}

cspoo_swiftmailer_mailgun:
    #key: "key-ebd2508e9c7346eb95c5eea86240029d"
    #domain: "sandboxfa8c7f17ce114f1b939e5dd2937d6588.mailgun.org"
    key: "key-13587873277bfb8194c52290c0850753"
    #domain: "sandboxd55b4a445a5948409dc77ea13bef9d5a.mailgun.org"
    domain: "testhichem1.mdprc.com"

nicomak_paypal:
    email: "events@nicomak.eu"
    confirm_route: "payment_credits_confirm"
    cancel_route: "payment_credits_cancel"

snowcap_im:

  # the timeout in seconds for the imagemagick process (optional). Default: 60
  timeout: 300

  # optional too, a list of pre-defined conversions
  formats:
    # resizes to 50 width, at 80% quality
    small:
      resize: 50x
      quality: 80

    # resizes to fit in 100x100, only if bigger, and remove all crap (meta-data, ...)
    medium:
      thumbnail: 100x100>

    # crop to get exactly 100x100, keeping the maximum area possible, centered
    square:
      resize: 100x100^
      gravity: center
      crop: 100x100+0+0

cmen_google_charts:
    version: "current"

#enable intl extensions
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }