# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_COMMERCIAL:  [ROLE_USER]
        ROLE_COMPTA:  [ROLE_USER]
        ROLE_NDF:  [ROLE_USER]
        ROLE_COMMUNICATION:  [ROLE_COMMUNICATION]
        ROLE_RH:  [ROLE_RH]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                invalidate_session: false #this prevents a php error - it should be removed and fixed by upgrading php to minimum 5.4.11
            anonymous:    true
            remember_me:
              key:      "%secret%"
              lifetime: 2592000
              path:     /
              domain:   ~
              user_provider: fos_userbundle
            switch_user: true

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/emailing/campagne/lancer, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1  }
        - { path: ^/crm/contactwebForm/addContactWeb, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/wp-register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirm/^, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/crm/contactwebForm/addContactWeb, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/crm, role: ROLE_COMMERCIAL }
        - { path: ^/ndf, role: ROLE_NDF }
        - { path: ^/compta, role: ROLE_COMPTA }
        - { path: ^/emailing, role: ROLE_USER }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/superadmin/, roles: ROLE_SUPER_ADMIN }
